### ISSUE TITLE
CivitAI not working somehow

### ISSUE THREAD

**Issue by etherealxx** [etherealxx/batchlinks-webui#12]
If you guys also found out about the CivitAI problem, please comment down below with the screenshot of your error message. I will find the culprit of this mess🙏

**Comment by etherealxx** [comment]
Currently CivitAI website is going down partially. So some of your download might not work. Use the direct link method instead.

**Comment by Animeseeker** [comment]
![IMG_20230315_004424](https://user-images.githubusercontent.com/127879172/225080312-c9d0acaf-e340-4a51-89c2-c61132528038.png)
CiviAI note working

**Comment by etherealxx** [comment]
> [![IMG_20230315_004424](https://user-images.githubusercontent.com/127879172/225080312-c9d0acaf-e340-4a51-89c2-c61132528038.png)](https://user-images.githubusercontent.com/127879172/225080312-c9d0acaf-e340-4a51-89c2-c61132528038.png) CiviAI not working

can you give me the link of the model please? does the problem still exist now? You seems like clicking the cancel button, aren't you?

**Comment by Animeseeker** [comment]
I didn't click the cancel button all the CivitAi models not working
Here's the link:

https://civitai.com/models/3745/anytwam-11-mixedmodel
 https://civitai.com/models/1845/darkberry-mix-99a1a2f6
https://civitai.com/models/2583/grape-and-grapefruit-hentai-models
https://civitai.com/models/1368/mitsudoue-model

Here's the screenshot's

![IMG_20230315_083841](https://user-images.githubusercontent.com/127879172/225174242-5d33cba4-79fb-46ff-963f-889a69a5463d.png)

![IMG_20230315_084659](https://user-images.githubusercontent.com/127879172/225174902-eaabcbfa-421c-43bc-b2df-b55e77c598fa.png)

![IMG_20230315_084735](https://user-images.githubusercontent.com/127879172/225174995-76cf82a6-ef1c-46bf-b7ad-4f1f12740e7c.png)

![IMG_20230315_084936](https://user-images.githubusercontent.com/127879172/225175075-47c3b8fb-866a-442b-bd37-a2914278c0de.png)

**Comment by etherealxx** [comment]
@Animeseeker sorry your answer didn't get into my notification yesterday.

So we're talking about Etherportal right? Which is kinda weird since this issue page is the issue page of batchlinks, not Etherportal. But nonetheless, that's still my repo.

About your problem, i think the owner of the model moved the model into somewhere else, or deleted it, or updated it.

I'm currently busy developing this batchlinks extension, so that Etherportal colab may seems unmaintained.

But i'll try to move all the models into huggingface instead, and i'll update those links. Thank you for reminding me✨

**Comment by Animeseeker** [comment]
👍👍

**Comment by anda-ren** [comment]
I got `KeyError: 'content-type'` when downloading civitai artifacts

## mylinks
```
#lora
https://civitai.com/models/76937/hairstyles-collection
````

## The error output
```

https://civitai.com/models/76937/hairstyles-collection
Traceback (most recent call last):
  File "/mnt/data/renyanda/.local/bin/gdown", line 8, in <module>
    sys.exit(main())
  File "/mnt/data/renyanda/.local/lib/python3.8/site-packages/gdown/cli.py", line 156, in main
    filename = download(
  File "/mnt/data/renyanda/.local/lib/python3.8/site-packages/gdown/download.py", line 178, in download
    if res.headers["Content-Type"].startswith("text/html"):
  File "/usr/local/lib/python3.8/dist-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-type'
Downloading...
From: https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/795f422c-0b12-4089-9449-2e7cb2f333e0/width=450/1193246.jpeg
To: /mnt/data/renyanda/code/stable-diffusion-webui/models/Lora/baldie_hairstyle.jpg

0.00B [00:00, ?B/s]
26.4kB [00:00, 160kB/s]
26.4kB [00:00, 160kB/s]
/mnt/data/renyanda/code/stable-diffusion-webui/models/Lora/baldie_hairstyle.safetensors successfully downloaded.
```

## The screenshots
![image](https://github.com/etherealxx/batchlinks-webui/assets/89630947/1f21fb78-1c66-410b-838d-b20c21ec03a2)
![image](https://github.com/etherealxx/batchlinks-webui/assets/89630947/5f6e2d37-d273-4439-8e4f-fcc246bf5c8f)
