### ISSUE TITLE
Got a codec error in download process

### ISSUE THREAD

**Issue by nemuruibai** [etherealxx/batchlinks-webui#16]
![image](https://user-images.githubusercontent.com/39950653/226754403-b1b6b9f2-93fe-47f1-ab71-d2c2486e1e34.png)
like this.

**Comment by etherealxx** [comment]
hello👋 can you send the text version instead into this thread? copy paste it maybe? thank you.

**Comment by etherealxx** [comment]
I think i found the problem. My method to check if aria2 is installed or not is by calling it with subprocess.getoutput. I think i'll change the method into `if os.path.exists` instead.

**Comment by nemuruibai** [comment]
> hello👋 can you send the text version instead into this thread? copy paste it maybe? thank you.

oh,of course.
————————————————————————————————————————————
Traceback (most recent call last):
  File "F:\AI Art Tools\stable-diffusion-webui_2301\python\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\AI Art Tools\stable-diffusion-webui_2301\python\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "F:\AI Art Tools\stable-diffusion-webui_2301\python\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\AI Art Tools\stable-diffusion-webui_2301\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\AI Art Tools\stable-diffusion-webui_2301\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "F:\AI Art Tools\stable-diffusion-webui_2301\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\AI Art Tools\stable-diffusion-webui_2301\extensions\batchlinks-webui\scripts\batchlinks-downloader.py", line 1430, in run
    civitdown2(currentlink, currentfolder, choosedowner, currenttorename, False, civitdefault, civitpruned, civitvae)
  File "F:\AI Art Tools\stable-diffusion-webui_2301\extensions\batchlinks-webui\scripts\batchlinks-downloader.py", line 746, in civitdown2
    hfdown(data_url, data_save_path, downloader, currentmode)
  File "F:\AI Art Tools\stable-diffusion-webui_2301\extensions\batchlinks-webui\scripts\batchlinks-downloader.py", line 877, in hfdown
    checkaria = subprocess.getoutput(ariapath)
  File "F:\AI Art Tools\stable-diffusion-webui_2301\python\lib\subprocess.py", line 643, in getoutput
    return getstatusoutput(cmd)[1]
  File "F:\AI Art Tools\stable-diffusion-webui_2301\python\lib\subprocess.py", line 624, in getstatusoutput
    data = check_output(cmd, shell=True, text=True, stderr=STDOUT)
  File "F:\AI Art Tools\stable-diffusion-webui_2301\python\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "F:\AI Art Tools\stable-diffusion-webui_2301\python\lib\subprocess.py", line 503, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "F:\AI Art Tools\stable-diffusion-webui_2301\python\lib\subprocess.py", line 1139, in communicate
    stdout = self.stdout.read()
  File "F:\AI Art Tools\stable-diffusion-webui_2301\python\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 4: invalid continuation byte
————————————————————————————————————————————



> I think i found the problem. My method to check if aria2 is installed or not is by calling it with subprocess.getoutput. I think i'll change the method into `if os.path.exists` instead.

got it,thank you so much

**Comment by etherealxx** [comment]
@nemuruibai hello👋 i hopefully fixed the thing now. I checked it with a virtual machine to make sure it work.

Also remember that you need to makes sure that you add python 3.10 to PATH when you were installing Python before

![python](https://user-images.githubusercontent.com/64251396/227112126-b74794b0-aad5-4839-8cf9-1bc734258a51.png)
