### ISSUE TITLE
Creating a tag without downloading anything into the folder causes error

### ISSUE THREAD

**Issue by marouane-erouhi** [etherealxx/batchlinks-webui#26]
Creating a custom tag like this without specifying any downloads causes the extension to break until UI restart.
`@new #000None /content/stable-diffusion-webui/models/Lora/000None`

This does create the empty folder, but breaks for any subsequent downloads.

I do this to create an empty directory that I use as a makeshift filter.
Feel free to delete this if it's not part of the project scope.

Here is the stack trace:
```
Adding custom path failed! Reason: unexpected EOF while parsing (<string>, line 1)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.9/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/content/stable-diffusion-webui/extensions/batchlinks-webui/scripts/batchlinks-downloader.py", line 1692, in run
    downloadedfiles = writeall(oldfilesdict, isshell, addedcustompath)
  File "/content/stable-diffusion-webui/extensions/batchlinks-webui/scripts/batchlinks-downloader.py", line 1116, in writeall
    newdict = trackall()
  File "/content/stable-diffusion-webui/extensions/batchlinks-webui/scripts/batchlinks-downloader.py", line 1162, in trackall
    exec(f"os.makedirs({x}path, exist_ok=True)")
  File "<string>", line 1
    os.makedirs(000Nonepath, exist_ok=True)
                   ^
SyntaxError: invalid syntax
```

**Comment by etherealxx** [comment]
@marouane-erouhi is it because you use numbers on your folder name? Try without number.

as i store the folder name as a python variable, it can't start with a number.
![image](https://user-images.githubusercontent.com/64251396/232261384-71828462-620a-4975-adaa-90de1ac15b93.png)

Either way, i'll make an error detection for that, thanks!
