### ISSUE TITLE
some model in civitai cannot download

### ISSUE THREAD

**Issue by geniusshiun** [etherealxx/batchlinks-webui#28]
When download this model https://civitai.com/models/10028/neverending-dream, the error code is below:
```
https://civitai.com/models/10028/neverending-dream
Traceback (most recent call last):
  File "/user/.local/lib/python3.10/site-packages/gradio/routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "/user/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "/user/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1022, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/user/.local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/user/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/user/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/user/stable-diffusion-webui/extensions/batchlinks-webui/scripts/batchlinks-downloader.py", line 1607, in run
    civitdown2(currentlink, currentfolder, choosedowner, currenttorename, False, civitdefault, civitpruned, civitvae)
  File "/user/stable-diffusion-webui/extensions/batchlinks-webui/scripts/batchlinks-downloader.py", line 801, in civitdown2
    data_index, data_url, data_filename = civitmodeltypechooser(model, isprunedmodel, modeldefaulttype, civitlinkandnames) #@note
ValueError: too many values to unpack (expected 3)
```

**Comment by etherealxx** [comment]
@geniusshiun hi👋 thanks for the report. Civitai changes t's api rapidly these days, and i'll try to keep up with them.

**Comment by etherealxx** [comment]
I have made a branch that hopefully fix this problem. if you know how to, you can check by using this command to download the fixed version.
```
!git clone -b civittweak+uioverhaul https://github.com/etherealxx/batchlinks-webui /content/stable-diffusion-webui/extensions/batchlinks-webui
```
or, you can just wait several more hours for me to test this version more. i'll notify you when it's ready. (and if you're on local installation you can git pull later)

**Comment by geniusshiun** [comment]
Using origin version, download this [link](https://civitai.com/models/3666/protogen-x34-photorealism-official-release) .safetensors, and get .ckpt.
After checkout branch "civittweak+uioverhaul", this problem is fixed.
The issue I've reported is fixed, too.
Tkank you.

**Comment by etherealxx** [comment]
Patch v3.2.1 released. This bug was fixed. Again, thanks for the report🙏

Though, i have new problem that i couldn't solve (https://github.com/etherealxx/batchlinks-webui/issues/29). If you're free and willing to help, really appreciated😁✨
