### ISSUE TITLE
completely stopped working for me after AUTO1111 webui 1.6

### ISSUE THREAD

**Issue by vt-idiot** [etherealxx/batchlinks-webui#40]
I am on Google Colab, with /models/Lora hard linked to a Google Drive folder, not sure if that matters, but it's always worked just fine with this extension in the past.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/content/stable-diffusion-webui/extensions/batchlinks-webui/scripts/batchlinks-downloader.py", line 1292, in run
    oldfilesdict = trackall()
  File "/content/stable-diffusion-webui/extensions/batchlinks-webui/scripts/batchlinks-downloader.py", line 1210, in trackall
    exec(f"os.makedirs({x}path, exist_ok=True)")
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/content/stable-diffusion-webui/models/Lora'
```
I'm not sure why it's trying to make a directory that already exists. Is there a `mkdir` somewhere in here without `-p` or without a check to see if the directory exists?

**Comment by vt-idiot** [comment]
Eh. Disregard that, just Google Colab being stupid again. Rebinding the mount made it start working again.
`mount --bind /content/drive/MyDrive/Lora/ /content/stable-diffusion-webui/models/Lora/`
